### ISSUE TITLE
Submitted jobs compile the library each time before to make the minitree

### ISSUE THREAD

**Issue by lucrlom** [XENON1T/cax#118]
Dear all,

I think is necessary the attention of somebody much more expert about python compiler an the core of cax.
Basically each time we submit a job, instead to read the already existing shared library, the single job recompile again the libraries necessary to run hax and then the minitree.

They are create each time with a different name:
`ROOT.TUnixSystem.ACLiC: INFO     creating shared library /home/mklinton/.cache/rootpy/x86_64-60403/dicts/78bda14f00fbee90.so`

is there some idea how and where define the shared library to be readed?

To compile from scratch these library cax take a lot of time and seem to stuck the hard disks

**Comment by pdeperio** [comment]
@tunnell any idea what's changed?  i think this used to not happen... why would each run now require a different library name for each dictionary?

**Comment by tunnell** [comment]
This is buried into rootpy so maybe something changed there?  This actually isn't "handled" by cax/pax.  It would be best if we understood this GRID mode in rootpy by maybe emailing the developers since they have some ways to avoid this.

**Comment by pdeperio** [comment]
I thought this was all fixed/constant in @remenska's [NLeSC libraries](https://github.com/NLeSC/root-conda-recipes)? i.e. the following installed packages shouldn't be changing, right?
```
root                      6.04             py3.4_gcc4.8.2    NLeSC
root-numpy                4.4.0            root6.04_py3.4    NLeSC
root_numpy                4.3.0            root6.04_py3.4    NLeSC
root_pandas               python3                nppy34_2    NLeSC
rootpy                    master                    py3.4    NLeSC
```
