### ISSUE TITLE
Duplicate sub-directories being created on data transfer

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#14]
Duplicate directory of dataset is sometimes created inside existing directory. I think likely due to datasets that take longer to transfer than the cax runtime period (currently 10 minutes), i.e. should add protection against starting a new transfer when one is already in progress or status "transferring".

**Comment by JelleAalbers** [comment]
This sounds like an artifact of running it via `watch -n 600`, right? Maybe we can use a different restart system, e.g. a few-line bash script like this: http://stackoverflow.com/questions/696839/how-do-i-write-a-bash-script-to-restart-a-process-if-it-dies

**Comment by pdeperio** [comment]
Actually I was referring to the scp processes that cax spawns internally. But now I read the logic more carefully here:

https://github.com/XENON1T/cax/blob/master/cax/tasks/data_mover.py#L99

and it seems like it does bypass copying if a DB entry at the remote site exists with any status (even "transferring" and "error"). So I don't know anymore what could have caused those duplicate directories.

Also, we have another transfer error now with a very large dataset (Run 538) that may be related. (p.s. Could you show me how you cleaned up these entries in the DB in order to retry? RE. https://github.com/XENON1T/cax/issues/13)

**Comment by tunnell** [comment]
Example?

**Comment by pdeperio** [comment]
Closed until it shows up again
