### ISSUE TITLE
Loop over tasks per dataset

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#26]
Currently, main.py loops over tasks and then loops over all datasets for each task. 

Instead might be better to loop over all datasets instead, and perform the tasks for each dataset, in case of transfer backlogs.

**Comment by tunnell** [comment]
Hope we just don't have backlogs :)  But I've been thinking this too.  Having tasks that take a while go to the batch queue could also help... like if tasks could be generalizable to be batch-queable.

**Comment by pdeperio** [comment]
True, copying your Gitter comment:
> The mutli-scp work would be as follows: start with processing code, generalize into Task base class that takes an argument of the command to run, then turn process/scp/any task into a batch job.  Maybe each Task can define 'batch = False' or 'batch = True'
