### ISSUE TITLE
massive-cax 5-minute checks not working

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#33]
massive routine:

https://github.com/XENON1T/cax/blob/master/cax/main.py#L162

seems to not work (not getting files that require action)

**Comment by tunnell** [comment]
We could also just submit jobs for runs in the last few days every hour.  Then everything once a day.  Logic is probabily easier.

**Comment by tunnell** [comment]
Fixed.  Just look at data from last two days.
