### ISSUE TITLE
Interfacing Rucio with cax

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#36]
## Raw data distribution

cax -> Rucio proposed data flow:
1. cax daemon running on xe1t-datamanager as usual
2. New task which copies raw data from `/archive/xenon1t/rawdata/runs` to temporary cache space (can be just some other directory), then registers to Rucio catalog and resulting Rucio ID to RunsDB 
3. Rucio takes over data distribution from here

Benedikt provided some code for step 2, which we should now implement and test:

"To determine the local file path that needs to be created and the file has to be copied to at the LNGS endpoint:

``` python

    def _get_path(self, scope, name):
        """ 
        Transforms the logical file name into a PFN.
        Suitable for sites implementing the RUCIO naming convention.

        :param lfn: filename
        :param scope: scope
        :returns: RSE specific URI of the physical file
        """
        hstr = hashlib.md5('%s:%s' % (scope, name)).hexdigest()
        if scope.startswith('user') or scope.startswith('group'):
            scope = scope.replace('.', '/')
        return '%s/%s/%s/%s' % (scope, hstr[0:2], hstr[2:4], name)
```

I have also attached the rucio upload code with extra comments."

[rucio_upload_example.py.zip](https://github.com/XENON1T/cax/files/407652/rucio_upload_example.py.zip)
## Processing

To be flushed out later, but in principle:
1. cax will need to grab Rucio ID from RunsDB to pass to each job script
2. Job script takes Rucio ID and uses Rucio client to grab raw data
3. Job script calls pax to process raw data
4. Job script then makes copy and registration of processed file to some Rucio endpoint

**Comment by XeBoris** [comment]
Is there an easy way to setup a cax-rucio test set up? For example: Installation of a modified cax-rucio branch at xe1t-datamanager and make use of some test files for upload there?

**Comment by tunnell** [comment]
Patrick uses custom Cax.json for this

**Comment by pdeperio** [comment]
Also, check the "Installing cax" section of the README (https://github.com/XENON1T/cax) for how to create your own local installation.

**Comment by pdeperio** [comment]
Implemented in https://github.com/XENON1T/cax/pull/67 and https://github.com/XENON1T/cax/pull/67
