### ISSUE TITLE
Allow passing of custom cax.json through command line

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#4]
Would be nice to be able to pass custom cax.json's to cax-single and cax commands.

**Comment by tunnell** [comment]
Why?

**Comment by pdeperio** [comment]
Just for development and testing now

**Comment by tunnell** [comment]
Do we really want this?  It seems like it would make stray cax instances that we didn't know what it was doing.

We can have it so you can specify your own cax.json, but then it writes to a dummy run DB and dummy locations?  Would this help?

**Comment by pdeperio** [comment]
Actually that sounds good, depending on the effort required and how much more you think we need to develop cax.

**Comment by pdeperio** [comment]
Implemented in https://github.com/XENON1T/cax/pull/18
