### ISSUE TITLE
MV runs with errors

### ISSUE THREAD

**Issue by pietrodigangi** [XENON1T/cax#63]
List of MV runs showing **error at midway-login1** step
since 1 nov 2016:

Num.
~~161108_1458~~	
~~161108_2058~~	
~~161109_1648~~	
~~161113_1009~~	
161116_1838	
161117_1713	
~~161119_1245~~	
161120_1044
161120_1644
161120_2245
161121_1813	
161122_1108
161122_1705
161122_2305	
~~161124_0030~~	
~~161124_1619~~	
~~161124_1659~~	
~~161125_0530~~	
~~161125_1620~~	
161125_1652	
~~161126_2013~~		
~~161127_1415~~		
161127_2015	
161128_0215	
161128_0816	
~~161130_2314~~	
~~161201_0514~~	
161202_1116
161202_1515
161202_2115
161203_0315
161203_2116
161204_0316
161204_1516
161204_2117

**Comment by pdeperio** [comment]
Old version of transfer/processing.
