### ISSUE TITLE
Metadata availability

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/cax#73]
Each raw data folder includes three metadata files:
  * acquisition_monitor_data.pickles
  * trigger_data.zip
  * eventbuilder.log (less important)

These are relatively small (< GB/hour during our highest-rate Rn220 runs), and hax can extract valuable metadata from them, such as the proximity of busy signals or muon veto triggers, and the dark rate of PMTs each second. I expect we will soon make more use of these in analysis.

Would it be possible to restore these files to midway even for datasets for which the raw data has been relocated? It's ok if they are renamed (so you could put them all in one folder) or if they aren't tracked by the runs db, I can find a way to deal with this in hax.

**Comment by tunnell** [comment]
For new data, should just be plugin that checks for raw data then copies just that file out somewhere new

**Comment by pdeperio** [comment]
Can follow e.g. https://github.com/XENON1T/cax/blob/master/cax/tasks/process_hax.py and just replace hax with a copy command.

Anyone can try to implement this? @lucrlom?

**Comment by JelleAalbers** [comment]
Solved by @ershockley, thanks!
