### ISSUE TITLE
Automake proximity minitrees

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/cax#76]
It would be nice if cax could build the proximity minitrees automatically, so we can start defining cuts on e.g. the proximity of a busy, or muon veto trigger, or the previous event (like the time difference cut in XENON100). 

It's not as simple as adding it to the list here:
https://github.com/XENON1T/cax/blob/master/cax/tasks/process_hax.py#L54

as this minitree needs access to the raw data. That means we have to set raw_data_local_path correctly here:
https://github.com/XENON1T/cax/blob/master/cax/tasks/process_hax.py#L23

However that probably depends on which site hax is running, or can perhaps bubble up from the deeper circles of cax.

**Comment by pdeperio** [comment]
Added in https://github.com/XENON1T/cax/commit/eea98276ead5963d6361b784f6070eca2aaabfd7

And I guess hax is initializing ```raw_data_local_path``` properly by default already (since we've been getting the Proximity minitrees for a while now).
