### ISSUE TITLE
Corrections versioning

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#81]
Note to ourselves: we should figure out how to version all our corrections.

**Comment by pdeperio** [comment]
This becoming more critical now with e.g. lifetimes being derived from different pax versions and the need to compare (process with) them simultaneously.

**Comment by pdeperio** [comment]
Fixed in https://github.com/XENON1T/cax/pull/95

@coderdj You happy with this now and can close?

**Comment by coderdj** [comment]
Yes. We're basically rolling everything except the gain and the NN back out of cax soon so we just have to take care to give those two the same versioning scheme.
