### ISSUE TITLE
Switch to dedicated Midway user for data tasks

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#87]
Since Chris has started to use his account more for analysis on Midway, we should start thinking of migrating everything to the dedicated account ```mklinton```. Probably after first result to not interfere with anything now, but should start thinking of everything that needs to be changed and potential problems (e.g. ownership, permissions).

**Comment by lucrlom** [comment]
Do you know where I have to check in the code to change the instances to the tunnell account??
Thanks

**Comment by lucrlom** [comment]
I get this one:
https://github.com/XENON1T/cax/blob/master/cax/qsub.py#L97

**Comment by lucrlom** [comment]
this one
https://github.com/XENON1T/cax/blob/master/cax/tasks/filesystem.py#L27

**Comment by lucrlom** [comment]
only that one, do you agree??

**Comment by pdeperio** [comment]
yes, also maybe the .json (for file transfers mainly i think). 

and @ershockley should change his OSG post-script too

**Comment by lucrlom** [comment]
I changed the username in both the files and in all *.json files in the `cax/cax/` directory.
Let me test and I will make a pool request

**Comment by lucrlom** [comment]
lack of permission to write on massive_cax.log. 
I will create a new one from the new account

**Comment by lucrlom** [comment]
Ok, Seems work properly now. All problems related to the ownership seem to be fixed.

**Comment by lucrlom** [comment]
The ownership of the old file is still present. We need to change the ownership in the raw and processed directory by means of root operator. There is no other way I think.

**Comment by lgrandi** [comment]
Ok, if we agree on this then @lucrlom please send an email to Igor putting me and patrick in cc please.

**Comment by pdeperio** [comment]
why do you need to change ownership?
