### ISSUE TITLE
Insert correction maps to use in run doc for processor

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/cax#90]
Now that we're starting analysis on runs with a different field, pax has to know which correction map to use for which runs. If we just include the new maps as default we could no longer process science run 0 or watch waveforms from it using newer pax versions. Probably it's enough to have one plugin choosing all correction maps based on either run time or cathode voltage (like #75).

Relates to #81.

**Comment by pdeperio** [comment]
@tunnell would you be able to eventually train someone on all the corrections? perhaps also with the goal of versioning?

**Comment by pdeperio** [comment]
I guess this is fixed in #95, right @JelleAalbers @coderdj ?

**Comment by coderdj** [comment]
Yes. We're already in the process of undoing a bit of our own work. ;-)
Closing.
